title: "Angry Data Scanner"
description: "Fast data scanner with friendly UI"
# Можно оставить встроенную тему Pages или без неё
plugins:
  - jekyll-seo-tag

permalink: /:path/

defaults:
  - scope:
      path: "en"
    values:
      layout: page
      lang: en
  - scope:
      path: "ru"
    values:
      layout: page
      lang: ru

# список языков (для шапки)
languages: [en, ru]