title: "Angry Data Scanner"
description: "Fast data scanner with friendly UI"
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

permalink: /:path/

defaults:
  - scope:
      path: "en"
    values:
      layout: page
      lang: en
  - scope:
      path: "ru"
    values:
      layout: page
      lang: ru

# список языков (для шапки)
languages: [en, ru]