name: Build Universal macOS .dmg

on:
  push:
    branches: [ main, develop, feature/* ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    strategy:
      matrix:
        build-type: [conveyor, compose]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew :desktop:build
      env:
        VERSION: ${{ github.ref_name }}

    - name: Install Conveyor (for conveyor build)
      if: matrix.build-type == 'conveyor'
      run: |
        curl -L https://keys.openpgp.org/download/keys/3C2C43D7267D5959FE7DA2D7B6BC98744E6E0F94 | gpg --dearmor > /usr/local/share/keyrings/hydraulic-archive-keyring.gpg
        echo "deb [signed-by=/usr/local/share/keyrings/hydraulic-archive-keyring.gpg] https://downloads.hydraulic.software/deb/ stable main" > /etc/apt/sources.list.d/hydraulic.list
        apt-get update
        apt-get install -y conveyor

    - name: Build with Conveyor
      if: matrix.build-type == 'conveyor'
      run: |
        cd desktop
        conveyor make --output-dir ../build/packages site
      env:
        VERSION: ${{ github.ref_name }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Compose Desktop
      if: matrix.build-type == 'compose'
      run: |
        cd desktop
        ./gradlew :desktop:packageDmg
      env:
        VERSION: ${{ github.ref_name }}

    - name: Find .dmg files
      run: |
        echo "=== Searching for .dmg files ==="
        find . -name "*.dmg" -type f -exec ls -la {} \;

    - name: Upload .dmg artifact (Conveyor)
      if: matrix.build-type == 'conveyor'
      uses: actions/upload-artifact@v4
      with:
        name: big-data-scanner-macos-conveyor-${{ github.ref_name }}
        path: build/packages/*.dmg
        retention-days: 30

    - name: Upload .dmg artifact (Compose)
      if: matrix.build-type == 'compose'
      uses: actions/upload-artifact@v4
      with:
        name: big-data-scanner-macos-compose-${{ github.ref_name }}
        path: |
          desktop/build/compose/binaries/main/dmg/*.dmg
          desktop/build/compose/binaries/main/app/*.dmg
        retention-days: 30

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-macos
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/big-data-scanner-macos-conveyor-*/**/*.dmg
          artifacts/big-data-scanner-macos-compose-*/**/*.dmg
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
