name: Build Linux

on:
  release:

jobs:
  Tests-Linux:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout Lib
        uses: actions/checkout@v4
        with:
          repository: packetdima/angrydata
          path: lib

      - name: Validate gradle wrappers
        uses: gradle/actions/wrapper-validation@v4

      - name: List files in the working directory
        run: ls -R

      - name: Tests with Gradle Wrapper and XVFB
        uses: coactions/setup-xvfb@v1
        with:
          run: ./gradlew allTests --no-daemon

  Build-Linux:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout Lib
        uses: actions/checkout@v4
        with:
          repository: packetdima/angrydata
          path: lib

      - name: Validate gradle wrappers
        uses: gradle/actions/wrapper-validation@v4

      - name: Set verion variable
        run: export VERSION=${{github.event.release.tag_name}}

      - name: Build with Gradle
        run: ./gradlew packageReleaseDeb

      - name: Get version
        run: ./gradlew printVersion

      - name: Upload artifact
        run: |
          gh release upload ${{github.event.release.tag_name}} './desktop/build/compose/binaries/main-release/deb/Big Data Scanner-${{github.event.release.tag_name}}.deb'
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}