name: Nightly build
on:
  pull_request:
  push:
    branches:
      - feature/conveyor-ci

jobs:
  Build-Convey:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate gradle wrappers
        uses: gradle/actions/wrapper-validation@v4

      - name: Install conveyor
        run: |
          wget https://downloads.hydraulic.dev/conveyor/conveyor-18.0-linux-amd64.tar.gz
          tar -xzf conveyor-18.0-linux-amd64.tar.gz
          chmod +x conveyor-18.0/bin/conveyor
          echo "$(pwd)/conveyor-18.0/bin" >> $GITHUB_PATH

      - name: Build and push with conveyor
        uses: coactions/setup-xvfb@v1
        with:
          run: ./gradlew conveyCI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-msix
          path: |
            desktop/build/packages/*.msix
            desktop/build/packages/*.crt
            desktop/build/packages/*.appinstaller
            desktop/build/packages/*.ps1
            LICENSE*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable
          path: |
            desktop/build/packages/*windows*.zip
            LICENSE*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-portable
          path: |
            desktop/build/packages/*.tar.gz
            LICENSE*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: |
            desktop/build/packages/*.deb
            LICENSE*

  Build-macOS:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate gradle wrappers
        uses: gradle/actions/wrapper-validation@v4

      - name: Build macOS DMG (Intel compatible)
        run: ./gradlew :desktop:packageReleaseDmg

      - name: Rename macOS DMG file
        run: |
          mkdir -p macos-nightly
          cp desktop/build/compose/binaries/main-release/dmg/*.dmg "macos-nightly/big-data-scanner-nightly_mac.dmg"
          cp LICENSE.txt LICENSE.en.txt macos-nightly/

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-nightly
          path: macos-nightly/*