name: release.yml
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  Build-Convey:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate gradle wrappers
        uses: gradle/actions/wrapper-validation@v4

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0

      - name: Build with Conveyor
        run: ./gradlew convey
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}

      - name: Tests with Gradle Wrapper and XVFB
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: ./gradlew allTests --no-daemon
