name: Tests Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Tests-Linux:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Checkout Lib
      uses: actions/checkout@v4
      with:
        repository: packetdima/angrydata
        path: lib

    - name: Validate gradle wrappers
      uses: gradle/actions/wrapper-validation@v4

    - name: List files in the working directory
      run: ls -R

    - name: Tests with Gradle Wrapper and XVFB
      uses: coactions/setup-xvfb@v1
      with:
        run: ./gradlew allTests --no-daemon

  Tests-Windows:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate gradle wrappers
        uses: gradle/actions/wrapper-validation@v4

      - name: Tests with Gradle Wrapper
        run: ./gradlew allTests
