name: Tests Linux

on:
  pull_request:
  push:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  Tests-Linux:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Checkout Lib
      uses: actions/checkout@v4
      with:
        repository: packetdima/angrydata
        path: lib

    - name: Validate gradle wrappers
      uses: gradle/actions/wrapper-validation@v4

    - name: List files in the working directory
      run: ls -R

    - name: Tests with Gradle Wrapper and XVFB
      uses: coactions/setup-xvfb@v1
      with:
        run: ./gradlew koverXmlReport --no-daemon

    - name: Test Reporter
      uses: dorny/test-reporter@v1.9.1
      if: success() || failure()
      with:
        name: JUnit Report
        path: '**/build/test-results/*/TEST-*.xml'
        reporter: java-junit


  Tests-Windows:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate gradle wrappers
        uses: gradle/actions/wrapper-validation@v4

      - name: Tests with Gradle Wrapper
        run: ./gradlew koverXmlReport

      - name: Test Reporter
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: JUnit Report
          path: '**/build/test-results/*/TEST-*.xml'
          reporter: java-junit