name: Tests

on:
  push:
  pull_request:

jobs:
  Linux:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Validate gradle wrappers
      uses: gradle/actions/wrapper-validation@v4

    - name: Tests with Gradle Wrapper and XVFB
      uses: coactions/setup-xvfb@v1
      with:
        run: ./gradlew allTests --no-daemon
